<?php

/**
 * @file
 * Contains o2e_obe_salesforce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function o2e_obe_salesforce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the o2e_obe_salesforce module.
    case 'help.page.o2e_obe_salesforce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module handles the connection with the O2E SF instance for ther OBE.') . '</p>';
      return $output;

    default:
  }
}
