# Schema for the configuration files of the salesforce module.

o2e_obe_salesforce.settings:
  type: config_object
  label: 'Salesforce Settings'
  mapping:
    sf_brand:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        brand:
          type: text
          label: 'Brand'
    sf_auth:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        login_url:
          type: text
          label: 'Login URL'
        api_username:
          type: text
          label: 'API username'
        api_password:
          type: text
          label: 'API password'
        grant_type:
          type: text
          label: 'OBE Grant Type'
        client_id:
          type: text
          label: 'OBE Client ID'
        client_secret:
          type: text
          label: 'OBE Client Secret'
        token_expiry:
          type: text
          label: 'Token Expiry'
    sf_verify_area:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        service_expiry:
          type: text
          label: 'Service Expiry'
        api_url_segment:
          type: text
          label: 'Api URL Segment'
        enable_ans:
          type: string
          label: Enable ANS
        ans_message:
          type: text
          label: ANS Message
    sf_available_time:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        services_type:
          type: text
          label: 'Services Type'
        api_url_segment:
          type: text
          label: 'Api URL Segment'
        show_holdtime_message:
          type: string
          label: Show Hold Time Message
        slot_holdtime_message:
          type: text
          label: HoldTime Message
        slot_holdtime_sub_message:
          type: text
          label: HoldTime Sub Message
    sf_promo_details_junk:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        api_url_segment:
          type: text
          label: 'Api URL Segment'
    sf_book_job_junk_customer:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        api_url_segment:
          type: text
          label: 'Api URL Segment'
        customer_type:
          type: text
          label: 'Customer Type'
    sf_book_job_junk:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        api_url_segment:
          type: text
          label: 'Api URL Segment'
    sf_hold_time:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        api_url_segment:
          type: text
          label: 'Api URL Segment'
    create_lead:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        api_url_segment:
          type: text
          label: 'Api URL Segment'
