<?php

/**
 * @file
 * Contains o2e_obe_common.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_help().
 */
function o2e_obe_common_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the o2e_obe_common module.
    case 'help.page.o2e_obe_common':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('O2E common settings') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_token_info().
 */
function o2e_obe_common_token_info() {
  $token_type['custom_webform_token'] = [
    'name' => t("Custom Webform Token"),
    'description' => t("Custom type grouping for webform tokens."),
  ];

  $token['confirmation-message'] = [
    'name' => t("Webform Confirmation Message"),
    'description' => t("This will show the webform confirmation message containing images."),
  ];

  return [
    'types' => $token_type,
    'tokens' => [
      'custom_webform_token' => $token,
    ],
  ];
}

/**
 * Implements hook_tokens().
 */
function o2e_obe_common_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type === 'custom_webform_token') {
    foreach ($tokens as $name => $original) {
      $config = \Drupal::config('o2e_obe_common.settings')->get('o2e_obe_common');
      switch ($name) {
        case 'confirmation-message':
          $wf_confirm_message = '';
          if ($config && !empty($config['obe_confirmation_message'])) {
            $wf_confirm_message = Markup::create($config['obe_confirmation_message']);
          }
          $replacements[$original] = $wf_confirm_message;
          break;
      }
    }
  }
  return $replacements;
}
